### ISSUE TITLE
config.push_notifs  config.resources

### ISSUE THREAD

**Issue by mqqgd** [Spider101/Visual-Semantic-Alignments#1] opened 2020-11-17 14:17 UTC
Hello and thanks for sharing your code and data.
May I know how to ceate config.push_notifs to run the code?I am learning your code ,Could you mind  providing me the config dictionary ? 
Thanks

**Comment by Spider101** [comment] 2020-11-17 17:08
Hi, sorry it has been a really long time since I touched this code, and as such have lost access to my original files and setup. Did you run the four steps in the prerequisite part of the README? As far as I remember that should set you up with everything you need. If so, can you reply with a screenshot of your directory structure so I can get an idea of what files were created and where? Additionally, if you can post the contents of your `config/resources.py` file, I can verify if all the variables have been set correctly.

**Comment by mqqgd** [comment] 2020-11-17 17:23
hi, I'm glad to hear from you. It's getting late here. May I show you during the day?I appreciate receiving your reply😆😆😆.

---Original---

**Comment by mqqgd** [comment] 2020-11-18 08:03
hello , thanks  for your reply.  I followed Prerequisites 3 and built a config directory .  Here is  config folder built. I dont know if it's right.  There is not a place to upload screenshot of my directory sturcture.(；′⌒`)...
So, I show you in words:

```
**import argparse
if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--local_data_path', type=str,
                        default='E:\Visual-Semantic-Alignments-master\config', 
                        help='path for data')
    parser.add_argument('--VG_IMG_FNAME', type=str, default='./config/visual genome image metadata/image_data.json',
                        help='path for visual genome image metadata')
    parser.add_argument('--VG_FEG_FNAME', type=str, default='./config/region description data/region_descriptions.json',
                        help='region description data ')
    parser.add_argument('--PARA_FNAME', type=str, default='./config/paragraph dataset/paragraphs_v1.json',
                        help='paragraph dataset')
    args = parser.parse_args()**
```

**I dont know what METADICT_FNAME is ..    
It is from code :   from config.resources import (local_data_path, VG_REG_FNAME, VG_IMG_FNAME, PARA_FNAME, METADICT_FNAME)
and I dont know how to write "from config.push_notifs import send_message",** 

 Can you recall how these files were created and where? I am looking forward to recieving your reply. 
(In addition, would you mind giving me your email? we can discuss it by email, and it's conveninent to show you the screenshot)

**Comment by Spider101** [comment] 2020-11-21 05:43
Hi, apologies for not getting back to you sooner. I'm not sure why you aren't able to upload the screenshot. Maybe this would help - [File attachments on issues and pull requests
](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests).

I'll try to follow the same steps locally over the weekend and see if there are any gaps in the instructions. If so, I can update the README.md by Monday at the earliest. In the meantime, it would be really helpful if you could post a screenshot of your directory tree for this project (via whatever text editor you are using) using the instructions from the link I posted above.

**Comment by mqqgd** [comment] 2020-11-23 12:56
![1](https://user-images.githubusercontent.com/37200439/99963741-2f4c3080-2dcd-11eb-960f-1a0125dd5cc2.PNG)
![2](https://user-images.githubusercontent.com/37200439/99963826-5440a380-2dcd-11eb-9384-1dbdbe6b4b2f.PNG)

**Thank you for your reply. I don't know much about github. I uploaded a screenshot based on the content in the url you sent. Can you see it? I can't find the content in the underlined area. I tried to write that module. I am just getting started with python and cannot reproduce your code, so I hope to get your help and look forward to your reply.**

**Comment by Spider101** [comment] 2020-12-12 14:06
Thanks for putting up the screenshots. I think I understand your question better now. My apologies for the delay in responding; I was swamped at work. I will try to look into this tomorrow.

My hunch is that the code doesn't match what I had put in the setup section of the README.md file. So, I will either update the readme or the code so it is easier to start working on the repo! 
Regarding the `send_message` import, you can ignore that as I had just written a script to send myself email notifications when the training checkpoints/results were ready. It is not essential for running the rest of the code. So, I will probably remove/replace that as well.

Cheers!

**Comment by Spider101** [comment] 2020-12-13 09:17
@mqqgd I have created a [PR](https://github.com/Spider101/Visual-Semantic-Alignments/pull/2) to help resolve some of these issues. Please take a look when you can and let me know if you can follow along. Otherwise, I will make some further updates. You should be able to reproduce everything till the 3rd point of the new __Getting Started__ section in the README.md file.

Once you confirm that you can, I will go ahead and merge the PR and resolve the other issues you were having. For example, the `push_notifs` issue.

**Comment by mqqgd** [comment] 2020-12-14 03:32
I am really grateful to receive your reply. I will check the PR first. If I encounter any problems, I will leave a message to you. Thank you for your help~

**Comment by Spider101** [comment] 2021-01-17 06:18
It's been a month since your last reply and I haven't received any feedback on the PR either. So, I have gone ahead and merged the PR and I am closing this issue. Feel free to open a new one if you face any other problems!

**Closed as completed by Spider101** 2021-01-17 06:18 UTC
Labels: question
